Traceback (most recent call last):
  File "download.py", line 12, in <module>
    cg = cggr.CGGR()
  File "/home/runner/work/CGGR/CGGR/cggr.py", line 7, in __init__
    self.GetInfo()
  File "/home/runner/work/CGGR/CGGR/cggr.py", line 21, in GetInfo
    self.info = json.loads(r.text)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
